NAME	=	static	
SRCS	=	convert.cpp convs.cpp
INCLUDE =	convert.hpp
OBJS	=	$(SRCS:.cpp=.o)
CC		= 	g++
RM		=	rm -rf
FLAGS	=	-Wall -Wextra -Werror -Wno-unused
STD	=	-std=c++98

all:		$(NAME)

${NAME} : ${OBJS} 
	${CC} ${OBJS} -o ${NAME} 

%.o : %.cpp $(INCLUDE)
	${CC} ${FLAGS} -c $< -o $@

clean:
			$(RM) $(OBJS) 

fclean:		clean
			$(RM) $(NAME)

re:			fclean $(NAME)

.PHONY:		all clean fclean re
